### ISSUE TITLE
makeffv1 - adjust folder path

### ISSUE THREAD

**Issue by raecasey** [kieranjol/IFIscripts#119]
adjust folder path to mirror the folder path used in the BAI ad project. Instead of logs,md5,video, xml - have objects, metadata, logs, - check folder path templates on the isis for confirmation of correct path.

**Comment by kieranjol** [comment]
Hey, this was added back in october in this commit: 
https://github.com/kieranjol/IFIscripts/commit/19f7204ac12f5ab8e1b35b3959cae00ab5ef873d
Here's a tree of the ffv1 file I just created:
![screen shot 2016-12-05 at 17 21 53](https://cloud.githubusercontent.com/assets/1127102/20894761/9973a3a2-bb0e-11e6-97f1-0384b39c42a8.png)
