### ISSUE TITLE
bitc - add watermark or timecode only options

### ISSUE THREAD

**Issue by kieranjol** [kieranjol/IFIscripts#121]
I need these every now and then, I'm sure others need them too
So -clean is already implemented
no extra argument produces bitc+watermark

-w should be watermark only
-t should be timecode only

**Comment by kieranjol** [comment]
srsly, add this  - it is needed

**Comment by raecasey** [comment]
can you assign me to one of these, - i'll see if I can do it over the wknd.

**Comment by kieranjol** [comment]
Sure, go for it. I'll have to figure out assignation on my end. You're better off trying both as the code will be very similar. This is easier to do if the bulk of the bitc code is repeated for the four options (watermark, bitc, both, none), but needs more thinking if done more efficiently. You can take a look at how the - clean option was added to get a sense of how that interacts with the default options. The least amount of repetition of identical code would be preferable as it is easier to maintain.

**Comment by kieranjol** [comment]
added here https://github.com/kieranjol/IFIscripts/commit/486182adff5c10430d8d10f4cddf4b2b16d91441
