### ISSUE TITLE
dcpaccess - Duration not honoured in converted access h.264 copy.

### ISSUE THREAD

**Issue by joshuatj** [kieranjol/IFIscripts#124]
Duration not honoured in converted access h.264 copy.

```xml
# There's a difference between intrinsic duration and duration.
 <IntrinsicDuration>1184</IntrinsicDuration>
 <EntryPoint>0</EntryPoint>
 <Duration>912</Duration>
```

The last 272 frames (1182-912) should have been cut off. 

```xml
# Reel XML from CPL
<Reel>
<Id>urn:uuid:cfc3d43d-5da7-4276-a8cf-57349fa0422d</Id>
<AssetList>
<MainPicture>
<Id>urn:uuid:b3a6a415-8cf1-4780-85ef-bfd6c117020d</Id>
<EditRate>24 1</EditRate>
<IntrinsicDuration>1184</IntrinsicDuration>
<EntryPoint>0</EntryPoint>
<Duration>912</Duration>
<Hash>YI+Xoy2gf8fQqmxv3GK27MwIdsY=</Hash>
<FrameRate>24 1</FrameRate>
<ScreenAspectRatio>1.85</ScreenAspectRatio></MainPicture>
<MainSound>
<Id>urn:uuid:65e8d43b-ee1a-4db9-af9d-b60fe3e302f3</Id>
<EditRate>24 1</EditRate>
<IntrinsicDuration>912</IntrinsicDuration>
<EntryPoint>0</EntryPoint>
<Duration>912</Duration>
<Hash>mb+zXSCYfPJ8OUTZRQdiHoVN/eU=</Hash>
<Language>en</Language></MainSound></AssetList></Reel>
```

**Comment by kieranjol** [comment]
Thanks for the report. I'll have to check, but I think the check in the
script might only kick in if entrypoint >0.  I've only seen these duration
elements used in one dcp from a vendor, so it's good to see that example.
Have you many cpls with that metadata?

**Comment by joshuatj** [comment]
This is only cpl I've encountered with this metadata. But I can imagine it is a legit use case. I guess it's not a very urgent feature.

**Comment by kieranjol** [comment]
It's totally legit and needs to be fixed. Actually now that I think of it, I think dcpaccess only looks for audio delays, not video.
Out of curiosity, is it just black at the end of the video file? The DCP that I have has` <Entry Point>` values of 240, and there are varying `<duration>` and `<intrinsicduration>` discrepencies in the audio only. There's silence and test beeps at the head, and silence at the tail. I think it's really interesting, it's basically head and tail leader in a DCP that is automatically trimmed and joined via the package!

**Comment by kieranjol** [comment]
ughhh, the proof is in the function name: https://github.com/kieranjol/IFIscripts/blob/master/dcpaccess.py#L150
It only checks for audio. I also think that the accuracy isn't perfect in terms of how I convert from frames to seconds as some rounding is done. I watched the h264 that was produced by that film with duratation values and the sync looked perfect, but this needs to be done better: https://github.com/kieranjol/IFIscripts/blob/master/dcpaccess.py#L172

**Comment by kieranjol** [comment]
Hi @joshuatj  - I'll get to this eventually, but I was wondering if you knew where projectors/playback tools derive the duration info from? Are they actually taking it from the CPL or is it buried somewhere within the MXF and the value is taken from there instead? I haven't looked myself but I should do.

**Comment by jeffreycs** [comment]
Hey @kieranjol, did you ever come up with a function to check for delay/duration in video? I was just trying to convert a single-reel DCP where the CPL lists the EntryPoint as "300" for each MXF – as expected, the first 300 frames of the audio track are excised, but the video retains its header. Like @joshuatj's case, this is the only CPL I've personally seen with this type of instruction, but it's worth noting.

Either way, your script has been invaluable in doing print traffic for an international film festival where I've had to make some tricky conversions from 25 to 24fps to play on outdated servers. Thank you so much for taking the time to develop this!

**Comment by kieranjol** [comment]
Hi @jeffreycs - thanks for getting in touch and I'm really delighted that you've been getting use out o the script. I hadn't anticipated your use case. I'm imagining that it's easier to change the fps on a prores file than seperate MXFS!
I had let this slip, but it would be great if you could provide me with your CPL (on github gist or something) and I can try to get this done over the weekend?

**Comment by jeffreycs** [comment]
It's a lot easier @kieranjol!! Subtitles are another issue, but your script lets me get all the heavy lifting with the video out of the way easily. Just sent you the CPL in question on gist.

**Comment by kieranjol** [comment]
Thanks!
Ah, the subtitles must be retimed too, I guess? I did some messing around with subs recently, let me know if you think I can help in some way.

**Comment by jeffreycs** [comment]
I would love to know the work you've been doing with subtitles! I didn't have to retime them, luckily - on this one in particular I just did a rudimentary 25 to 24 conversion in Compressor that kept the same runtime. The difficulty was arranging the subtitle reels in order (they weren't clearly marked with reel numbers, and the CPL was confusing, to me at least). Once I got the order figured out, I just placed all 7 of them where each reel would start (20 minutes in, 40 minutes in, 60 minutes in, etc) in DCP-o-matic's timeline. It would be great to have something like your XML-to-SRT converter that adjusts the start times of each subtitle relative to their actual start times in the whole feature, not just the particular reel. But without dcpaccess.py I wouldn't even have video, so thank you again for automating what would normally be the hardest step of this whole process! :100: :100: :100:

**Comment by kieranjol** [comment]
Interesting, I think your XML to SRT idea for multi-reelers should work off the top of my head. Also I just noticed that you have a slightly different duration case than Joshua had. His didn't have an EntryPoint value, just differing values for Duration and IntrinsicDuration - which probably means that the DCP doesn't want the tail of the video/audio to play. Your case is kind of the opposite, in that the DCP wants to remove the head of the mxfs. My example was a bit of both, the audio had to start 10 seconds late and finish ten seconds early, but the video didn't have any trimming requirements! Anyhow regardless, the same fix should work for all. I just need to find an easy way to add in a video delay check without lazy code repetition.

**Comment by jeffreycs** [comment]
Here's another example that combines all of the above! A single video MXF exits early but then re-enters at the exit point in reel 2, right as a new audio MXF comes in.

https://gist.github.com/jeffreycs/8d760957315f8efd52c72c42ef2b1770

Again it seems like the same fix would cover this one, as well.

**Comment by kieranjol** [comment]
haha wow, that one is quite clever. I have no idea why they would have made
a DCP like that though! it would be amazing if you could share the DCP with
me in some way, I can give you my email. I'd be able to fix this super
quick at home if that was the case. i can try to hack the CPLs from home,
but I'd have to test the code on a 120 gig 4k DCP at work which is the only
example of these in/outs that I have in a DCP.

**Comment by jeffreycs** [comment]
Unfortunately that DCP in question is 90 gigs and my current internet connection isn't nearly fast enough to send it over - we can probably figure something else out though, and I'd love to chat more about this all via email. My address is jeffreycarlsundin@gmail.com - I'm gonna delete the address once I post this but hopefully it will still show up in your email notification?

**Comment by kieranjol** [comment]
Yup, got it! Thanks, will shoot you an email.

**Comment by kieranjol** [comment]
I made a new branch - can ye check it out and see if it fixes your use cases? I have not tested on a real DCP - I've just manually edited test DCP CPLs.
https://github.com/kieranjol/IFIscripts/tree/dcpdelays
@joshuatj @jeffreycs

**Comment by jeffreycs** [comment]
I'm going to try it out today!

**Comment by joshuatj** [comment]
I know it's a bit late, but here's the full CPL with different duration and intrinsic duration https://gist.github.com/joshuatj/130c0bf054cad3da19958cb3ca125042

**Comment by kieranjol** [comment]
Thanks ya'll!

**Comment by kieranjol** [comment]
So I merged the fix just there. Let me know if the version of the script in git master solves the issue,
