### ISSUE TITLE
seq2ffv1 folder structure

### ISSUE THREAD

**Issue by raecasey** [kieranjol/IFIscripts#128]
so actually - when i said makeffv1 in my last issue - i meant seq2ffv1
would you be able to set up the folder structure for the output of seq2ffv1 to have the new folder path, - objects, metadata, logs

**Comment by kieranjol** [comment]
ah cool - will get on that in the new year.

**Comment by kieranjol** [comment]
Sorry that this took so long - the lack of use of this script in production + the dire state of the code meant changes were difficult.
