### ISSUE TITLE
rawbatch - aeo light premis xml log location

### ISSUE THREAD

**Issue by raecasey** [kieranjol/IFIscripts#136]
currently in the objects/audio folder
should be moved to the metadata/audio folder or logs/audio folder?

**Comment by kieranjol** [comment]
Ah yes, I think that this used to be moved in the old rawaudio script. Even though it is really a log file, I think it should be in metadata/audio. 
In rawbatch, I'll:
1. Check if the xml sidecar is in the source directory
2. Move it to the correct directory

And i can write a simple batch script that will move all sidecar xml files in objects/audio in to metadata/audio.

**Comment by kieranjol** [comment]
fixed here - https://github.com/kieranjol/IFIscripts/commit/a5aa6154381f1b516167e330f68f63043f9c75b2 - tested & works ok.
