### ISSUE TITLE
change name of rawbatch SIP manifest

### ISSUE THREAD

**Issue by raecasey** [kieranjol/IFIscripts#137]
from audio_manifest.md5 to raw_sip_manifest.md5

**Comment by kieranjol** [comment]
Good point, the manifest names in these scripts definitely need to be improved. The line in question is here if you'd like to change it yourself? Otherwise I can give it a go : https://github.com/kieranjol/IFIscripts/blob/master/rawbatch.py#L121

**Comment by kieranjol** [comment]
Eek - i put in the wrong line number last time:
https://github.com/kieranjol/IFIscripts/blob/master/rawbatch.py#L124

^

**Comment by raecasey** [comment]
cool, - thanks for encouraging me to do it myself.

**Comment by kieranjol** [comment]
not a bother, feel free to send on pull requests whenever. For small changes like these, you could just do a pull request and not bother raising an issue as the pull request ends up functioning as an issue too. Thanks again Raelene.
