### ISSUE TITLE
rename moveit.py to copyit.py

### ISSUE THREAD

**Issue by kieranjol** [kieranjol/IFIscripts#167]
Hey,

moveit.py is really misleading as it sounds like a cut/paste job where the source file is deleted. As the script is really more of a copy/paste, then I think copyit.py is a better name. What do ye think?

**Comment by AnjaMahler** [comment]
Logically I agree. But I do like to move it, move it.

**Comment by raecasey** [comment]
I agree with Anja. I'd be in favour of keeping it.
As the script develops we can have different arguments that all it to do different things, i.e. moveit.py -ds which would delete source if the checksums match if we wanted to.
move it covers a wide range of types of moving. And essentially it's purpose is there for us to move things.

**Comment by felixmeehan** [comment]
Hey, I'd be in favour of the rename as copyit.py suggests that the source file will remain as it is in it's original location.

**Comment by raecasey** [comment]
but that then limits us to the use of the script for copying only.

**Comment by kieranjol** [comment]
I don't think that naming it `copyit.py` would prevent us from adding other options like `-ds`, but I have seen several instances where the name `moveit.py` has caused confusion. It's why I called `masscopy.py` that rather than `massmove.py`. I'm easy enough anyhow. Curious to know what @aoifefitz2016 thinks. @futuredays have a similar script called hashmove which deletes the source by default, and has a command line argument that does a copy/paste instead.. https://github.com/FutureDays/hashmove

**Comment by raecasey** [comment]
Hey

lets close this and change the name to copyit.py. 
That seems to have been the consensus and I've been persuaded.

R

**Comment by kieranjol** [comment]
noiceeeeeeeeeeeeeeeeeeeeeeeeeeeee

will do so when i merge the desktop manifest thingy tomorrow. One last time:
https://www.youtube.com/watch?v=ecSCaZ_XPlo

**Comment by AnjaMahler** [comment]
bahhahahaha! nice!

**Comment by kieranjol** [comment]
done!
