### ISSUE TITLE
via @raecasey - add -dcp option to sipcreator

### ISSUE THREAD

**Issue by kieranjol** [kieranjol/IFIscripts#187]
OK i had some extra ideas for this so wanted to jot down before I forgot:
 
* Take `-dcp` option to grab the ContentTitleText from CPL and use that as parent folder within objects
* That should be a function within ififuncs.py
* There should be a dcp_check() function so that if someone forgets to select `-dcp`, the script can say to the user: LOOKS LIKE THIS MIGHT BE A DCP, WANT TO USE CONTENTTITLETEXT AS PARENT?
* HOw to check for DCP: Is there a cpl, is there an Assetmap, a PKL, is there MXF files etc

**Comment by raecasey** [comment]
all good ideas

**Comment by kieranjol** [comment]
Most of this has been done except the automated check to see if a DCP is present.

**Comment by kieranjol** [comment]
I don't think we need the automated check...
