### ISSUE TITLE
duration check multiple inputs

### ISSUE THREAD

**Issue by aoifefitz2016** [kieranjol/IFIscripts#188]
Hello, 

Would it be possible to put -i somewhere in durationcheck.py for multiple inputs?

Thank you,

Aoife

**Comment by kieranjol** [comment]
Yes it is possible, let's get this done!

**Comment by kieranjol** [comment]
ummm, I'm so stupid, it already has that option, it's not a `-i` option, but you just need to do:
`durationcheck,py` /path/tofirstfolder /path/to/secondfolder etc etc

I could add a `-i` though for consistencies sake, functionality wouldn't change though.

**Comment by kieranjol** [comment]
Thank you!
