### ISSUE TITLE
sipcreator/makeffv1

### ISSUE THREAD

**Issue by raecasey** [kieranjol/IFIscripts#198]
could we do a sipcreator with a makeffv1 option.
sort of like loopline.py. so the arg parse might be -ffv1, - which will send the input out to ffv1.mkv?
we can develop it later then to add mezz or proxy options.

**Comment by kieranjol** [comment]
Hey, sounds great. We could do it the other way around though - have the FFV1/losslessness functionality in a completely seperate script or function that just creates an FFV1/MKV, no folder structure, no fixity, no metadata, no nothing. Then, there could be an option in makeffv1, `-sip`, that launches sipcreator.py

And in a way, all scripts could be scaled back like this. The scripts do something, but it's sipcreator that actually creates the package.

I think concat.py is working well like this where it is just creating an MKV with a log file, and then this gets wrapped up by sipcreator. We could think of a lot of the scripts like this, in that sipcreator is ultimately one of the last things that happen to them before they become an AIP.

**Comment by raecasey** [comment]
yes, perfect. even better. sounds great

**Comment by kieranjol** [comment]
Pretty sure you'd suggested something like that before anyhow in some shape
or form. Should hopefully be less work going forward as we just need to
worry about what goes in objects folder and what should go in logs, and sip
creator will hopefully be good enough to make consistent packages.

**Comment by kieranjol** [comment]
I've been thinking a bit more about this and for now, we can't just have a standalone MKV file that can be sent to `sipcreator.py`, as there are also framemd5 logs/metadata for the v210 object (this might  be shipped off to a seperate, dead object description eventually, but we're not there yet) , and for the MKV - as well as logs, so we'll have to think what's the best method moving forward to integrate sipcreator with scripts like this.
I'm starting to think that your initial suggestion might be best - add an FFV1/normalise argument to `sipcreator.py`, but further thought is needed.

**Comment by kieranjol** [comment]
Ok, more thinking on this as I'm working on refactoring `seq2ffv1` at the moment.
A possible workaround is that `makeffv1, seq2ffv1`, and all other scripts that create extra files as a result of their  processing can:
* export these extra files to an operating systems `/tmp` folder.
* all that appears in the destination folder is the output object file.
* `sipcreator` can be altered to grab these files in the `/tmp` folder and package them accordingly. Perhaps it's most scaleable to add `-metadata` and `-logs` argparse options.
* `sipcreator` can run by default on these scripts, but an `argparse` option can disable this.
* Check `concat/validate` to see how they handle the integration with `sipcreator`
