### ISSUE TITLE
makedpx log to desktop folder

### ISSUE THREAD

**Issue by raecasey** [kieranjol/IFIscripts#209]
makedpx.py is one of the scripts that sends it's log to the desktop instead of to the desktop folder. needs to be amended.

**Comment by kieranjol** [comment]
Cool, I'll get this sorted. Should be simple all going well.

**Comment by kieranjol** [comment]
Can you run update.py and see if this works? I can't test up here as I need a package created by rawbatch in order to properly test.

**Comment by raecasey** [comment]
when i update - it says  i'm behind the origin master by one commit
Your local changes to the following files would be overwritten by merge:
	makedpx.py
should i run gitpull?

**Comment by kieranjol** [comment]
That sounds like makedpx was edited locally at some stage recently? can you run `git diff` and post the output?

**Comment by raecasey** [comment]
what would the input be?
what the path i'm comparing?

**Comment by kieranjol** [comment]
Git diff doesn't need an input, if you run it when inside of
ifigit/ifiscripts, it tells you what changes have been made to the local
git repository. My guess is that there are some local edits in there that
will prevent the git pull. Git doesn't want to overwrite anything and
assumes you might want to keep those edits.

**Comment by kieranjol** [comment]
so if in your home folder:
```
cd ifigit/ifiscripts
git diff
```

**Comment by raecasey** [comment]
diff --git a/makedpx.py b/makedpx.py
index 7c709f3..5d0687b 100755
--- a/makedpx.py
+++ b/makedpx.py
@@ -192,6 +192,7 @@ for source_directory in all_files:
             split_path                  = os.path.split(os.path.basename(source_directory))[1]
             start                       = datetime.datetime.now()
             source_manifest             = root_dir + '/%s_manifest.md5' % relative_path
+            print  source_manifest, 'source_manifest'
             generate_log(general_log, 'Generating source manifest via md5deep and storing as  %s' % source_manifest)
             make_manifest(root_dir, root_dir, source_manifest)
             info                        = make_framemd5(source_directory, 'tiff', 'tiff_framemd5')
@@ -212,6 +213,7 @@ for source_directory in all_files:
             generate_log(general_log, 'TIFF to DPX transcode complete')
             parent_basename =  os.path.basename(output_dirname)
             manifest_textfile = os.path.dirname(output_dirname) + '/' +  parent_basename + '_manifest.md5'
+            print manifest_textfile, 'manifest_textfile'
             generate_log(general_log, 'Generating destination manifest via md5deep and storing as  %s' % manifest_textfile)
             other = make_framemd5(output_dirname + '/image/dpx_files', 'dpx', 'dpx_framemd5')
             other_textfile = other[1]
macminis-mini:ifiscripts macmini$ ]

**Comment by kieranjol** [comment]
After the `git checkout makedpx.py && git pull`, all should be well. I can't vouch for this desktop_logs commit to work though, so let's see. I probably should have just put this in a branch actually.

**Comment by raecasey** [comment]
this worked. thanks.

**Comment by kieranjol** [comment]
Yay!

On 11 Aug 2017 15:19, "raecasey" <notifications@github.com> wrote:

this worked. thanks.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/kieranjol/IFIscripts/issues/209#issuecomment-321825650>,
or mute the thread
