### ISSUE TITLE
concat.py - argument choices

### ISSUE THREAD

**Issue by raecasey** [kieranjol/IFIscripts#212]
potentially ad arg parse to this so that you have a choice of not getting chapters if possible?
Also a choice of codec, - so prores mov instead of mkv.
this would open it up to less specific use.

**Comment by kieranjol** [comment]
Absolutely, that should be a simple enough fix. Do you need this soon? I think it should be just a few minutes work.
I might initially add `-prores` and `-nochapters` options, but down the line, there should be just 
`-codec` and `-container` options so the user can choose whatever they want, assuming that they are the values used by ffmpeg.

**Comment by kieranjol** [comment]
Actually this will take more work as more code needs to be changed. This script was envisaged as a stream copy tool, so the codec stream would just be copied.
Are your source files prores to begin with? If so, then it would change the scope of the script less to add
`-mov` and `-nochapters` options. `-mov` would just use MOV instead of Matroska.

**Comment by raecasey** [comment]
yes, - the source files would have the same codec and wrapper that it output file would have
in most cases, pro res

**Comment by kieranjol** [comment]
Cool, so another way of doing this would be to do a check at the start of the process so that the container could be determined, and the output would have the same container. For now, it'll be easier to add the `-mov` option as this more thinking is required for the other options.

**Comment by raecasey** [comment]
ok cool

**Comment by kieranjol** [comment]
pull request and instructions for checking out the branch and testing are over in https://github.com/kieranjol/IFIscripts/pull/213
