### ISSUE TITLE
sipcreator - tell it like it is

### ISSUE THREAD

**Issue by kieranjol** [kieranjol/IFIscripts#228]
So this should be renamed, along with documentation. This isn't rally a pre-ingest process dealing with a SIP - the SIP already exists and we are creating an AIP here as ingest has already begun. According to OAIS and @nkrabben https://twitter.com/NKrabben/status/935988904360062977

**Comment by raecasey** [comment]
'tell it like it is' is the name of one of my favourite songs!
https://www.youtube.com/watch?v=ZE-2x8tIgsE

i'm for this
there are circumstances where we are creating sips though, - like in the loopline tape ingests, where we are still using oe numbers.
we can differentiate different functions (in the broader sense of the term) for the command.

**Comment by kieranjol** [comment]
Great tune!

Yeah, I like the way CUNY avoid this and their similar-ish script is just called INGESTFILE. I think even for those loopline tape packages that still have the old OE numbers, I think they are partial AIPs and the ingest process is half way begun there cos we have some Representation Information and some PDI in there too. I think they were only ever SIPs when that original MOV or MKV existed prior to any scripts being run..

**Comment by nkrabben** [comment]
'There are only two hard things in Computer Science: cache invalidation and naming things.' -Phil Karlton

Not sure that there's a single great solution to what to call scripts, in the context of OAIS. It's terms and the practical use of those terms are too often at odds.

To go further down the road of OAIS pedantry, ingest is a functional entity in OAIS that includes receiving a SIP, QA, AIP Generation, Description Generation, and Coordinating Updates between Data Management and Storage functional entities. INGESTFILE seems to be doing portions of AIP Generation and Coordinating Updates.

**Comment by kieranjol** [comment]
Good points on all fronts, thanks for chiming in @nkrabben  - we'll never hit the nail fully on the head here. `littleBitOfIngest.py` is now the frontrunner.
