### ISSUE TITLE
makepbcore.py -include value =n/a for multiple fields

### ISSUE THREAD

**Issue by raecasey** [kieranjol/IFIscripts#261]
here are the fields where this needs to be included:
instantiationDimensi
instantiationLocatio
instantTimeStart
instantColors
instantLanguage
instantiationChanCon

**Comment by kieranjol** [comment]
All but `instantiationDimensi` are implemented locally.
I think for this one, we said that we wouldn't use it at all, as the information is covered elsewhere? Also it's a combination of height and scan type (1080p, 720p). I think it was a mistake that we left it in as included in the XDCAM format spreadsheet. Same for DCP.. I think that this could be removed from the database and not be included at all..

Also for `instantiationLocatio` - I can't remember how we would use this. The 'habitat' field in our database maps to this PBCore field, so having a seperate `instantiationLocatio` field might be a duplication of effort, unless we want to use this for barcodes or something? I'll check the minutes of our last meeting to see what was decided..

**Comment by raecasey** [comment]
yes re instantiationlocation. - it is the habitat field. we put it in as a yes, because we decided it was the same as the habitat field. i shouldn't have put it in the list above, sorry
R

**Comment by raecasey** [comment]
had a look over the pbcore template again there, - i think you are right. i think we said yes to dcp and xdcam but then re-thought it when it came to concat and converted, - but either neglected to revisit the subject for dcp and xdcam or just updating the field.
anyway, - it can be taken off the list and i'll adjust the pbcore template
R

**Comment by kieranjol** [comment]
Savage.  I've removed instantiationLocation and instantiationDimension just there, and all of the other fields produce 'n/a' for now. I'm gonna close this but re-open if necessary.
