### ISSUE TITLE
makepbcore - add annotation fields

### ISSUE THREAD

**Issue by raecasey** [kieranjol/IFIscripts#263]
the following fields need to be added:
Channel(s)
colour_range
format_version 
TimeCode_FirstFrame
TimeCode_Source
encoded  application company name
encoded  application name
encoded  application version
encoded  library name
encoded  library version

**Comment by raecasey** [comment]
i'[d trust your instinct on this. do you want to put it past Brian to see what he thinks? Or happy for you to go ahead with your suggestion if you're happy with it

R

**Comment by kieranjol** [comment]
I'll put the suggestion past @briancash and see what he makes of it.. Thanks Raelene.

**Comment by kieranjol** [comment]
timecode is the only one left to implement - working on that next.

**Comment by kieranjol** [comment]
All of these have been implemented. Timecode was added here: https://github.com/kieranjol/IFIscripts/commit/9a08f53fb2168068923ba90820fcaf1c25c95465 

Thanks for the issue, feel free to re-open if anything is not in order.
