### ISSUE TITLE
Validate.py detecting new files

### ISSUE THREAD

**Issue by rejveno** [kieranjol/IFIscripts#287]
Could validate.py be changed so it also detects new files in an aip/sip or folder that aren't listed in the manifest? 

That would be really useful for me to check older deliveries before accessioning them.

**Comment by kieranjol** [comment]
Yes it can, and it should. This should have been added a long time ago and it caught me out yesterday as well.

I can just re-use this function  from `copyit` - https://github.com/kieranjol/IFIscripts/blob/master/copyit.py#L272 -  so I think the work is already done. Also if you wanted to have a go at adding this, I'd be happy to guide/mentor the process. It should just be a copy paste job, then a LOT of testing. But perhaps another time if it suited better.

**Comment by raecasey** [comment]
hey
just following up with the solution we talked about yesterday.

when the script recognises that there is a different amount of files than are represented int he manifest, it lets you know the difference in the count and and asks you if you want to proceed with the validation or not.

**Comment by kieranjol** [comment]
Sound good to me!
