### ISSUE TITLE
normalise.py - remove copied xmls

### ISSUE THREAD

**Issue by raecasey** [kieranjol/IFIscripts#295]
mediainfo and mediatrace xmls are copied rather than moved from directory into sub directory and so are left next to the sip once the script has completed. would be great if they could be removed.

**Comment by kieranjol** [comment]
I agree, let's get rid of them!hopefully it's a quick fix. Thx for the
report!

**Comment by kieranjol** [comment]
OK, so it looks like this is a sipcreator default. It's working under the assumption that you might be processing a donation/delivery, and you don't want to cut/paste and delete the file at source when moving it into the supplemental subfolder.

So I'd be keen to continue having sipcreator behave this way for safety purposes and scalability, but I think adding a specific `os.remove()` call for the two xml files is the way to go.

What do you think?

**Comment by raecasey** [comment]
OK, so I need to sort this out ASAP for the DFXML for film scans stuff. So i'l try to get this sorted across the board.

**Comment by kieranjol** [comment]
OK, so I need to sort this out ASAP for the DFXML for film scans stuff. So i'l try to get this sorted across the board. (I was logged in as Raelene before so I deleted the comment!)

**Comment by kieranjol** [comment]
This has been resolved in both seq2ffv1 and in normalise.py
