### ISSUE TITLE
Use -lowres option for faster jpeg2000 decoding

### ISSUE THREAD

**Issue by matmat** [kieranjol/IFIscripts#298]
It would be useful to have the ability to use the -lowres input option in dcpaccess.py. This uses the already stored jp2k decomposition levels in the mxf and makes (re-scaled) decoding *much* faster. First found out about this here: https://www.belle-nuit.com/use-ffmpeg-for-dcp-playback

**Comment by kieranjol** [comment]
Very cool, I think I can easily add this.will properly look later. Thanks for the suggestion!

**Comment by kieranjol** [comment]
@matmat ,so would a `-lowres` option for dcpaccess that took values of `0,1,2` be sufficient?

**Comment by matmat** [comment]
Thanks! Yes I think that will be sufficient.

Maybe also an option to scale to an SD 16:9 container? (like the -hd option).

**Comment by kieranjol** [comment]
Ah cool, just to be clear, is the SD option square pixel? Something like 1024x576?

**Comment by kieranjol** [comment]
Hi @matmat ,sorry for the delay. This is added now, maybe make another issue for the -sd option?
Looks like the `-lowres 1` option for a flat container produces a horizontal resolution that is not divisible by two, which breaks libx264, but I guess that's outside of the scope of this script at the moment..
