### ISSUE TITLE
batchaccession for reproductions

### ISSUE THREAD

**Issue by kieranjol** [kieranjol/IFIscripts#300]
Currently, `batchaccession` is a very workflow specific script that needs to work in a much more general sense.
Here's what needs to be done:
* Generate a CSV parser that will analyse an Object Entry CSV such as this: 
```
OE No.,Date Received,Quantity,Format,Description,Contact Name,Type of Acquisition,Accession No.,Additional Information,Habitat,Vinegar No
OE-10702,14/08/2018,1,FFV1/PCM WAV Matroska,insert_fake_name_here,IFA,Reproduction,,Normalisation of OE-10650 | Representation of AF6564 | Reproduction of IFA (RD) 2014-46 | Capture,Rackstation/TK transfers,
```
* batchaccession should not ask for the filmographic number, instead it should parse it from the `Reproduction of` value.
* the `parent` should be extracted from the `reproduction of` value.
* the `dryrun` check should no longer be logfile specific, it should display the values that are parsed from the CSV
* the current loopline specific workflow should be maintained for the moment, but we should look into its eventual deprecation
* It remains to be seen if the filmographic CSV is even needed, seeing as the reference number and the title are already provided. It would be most accurate to extract the work's title from the filmographic CSV though.

That's all that I can see so far, there will surely be more...

**Comment by raecasey** [comment]
good to keep the loopline specific workflow and see how it can be adapted to another similar born digital or donation workflow in the future.

this new one I think will be adaptable for a number of different reproduction workflows
it still remains to be seen which ones exactly, - but I think if adding command arguments to batchaccession.py, it should be clear that this is a workfow for reproductions.

- parse the filmographic number from the 'Representation of' value in additional information field
- the parent is extracted from the 'Reproduction of' value in additional information field.
- the parent value is put in quotes so that it appears in the tech rec or the reproduction in the same way it appears in the source tech rec 
- filmographic csv is needed to be able to include csv of filmographic record of intellectual entity into aip

I can do all of the testing on this once the script is drafted.

**Comment by kieranjol** [comment]
Cheers @raecasey  - I'm going to try to keep it all within the same batchaccession script for now. Inititally i thought that the two different workflows were so different that they would demand a separate script, but I think most of the mechanisms involve a lot of cross-over.

**Comment by kieranjol** [comment]
I'll be at a point where I'll have a pull request soon, but here's the python `dictionary` of data that is parsed from the Object Entry CSV at this point:

```
{'reference number': 'AF6564', 'Object Entry': 'OE-10702', 'parent': 'IFA (RD) 2014-46'}
{'reference number': 'AA533', 'Object Entry': 'OE-10703', 'parent': 'IFA (RD) 2015-120'}
{'reference number': 'AB479', 'Object Entry': 'OE-10704', 'parent': 'IFA (RD) 2015-201'}
{'reference number': 'AD243', 'Object Entry': 'OE-10705', 'parent': 'IFA-2001-356'}
{'reference number': 'AD759', 'Object Entry': 'OE-10706', 'parent': 'IFA-2002-464'}
{'reference number': 'AD761', 'Object Entry': 'OE-10707', 'parent': 'IFA-2002-466'}
{'reference number': 'AF973', 'Object Entry': 'OE-10708', 'parent': 'IFA-2008-210'}
{'reference number': 'AF1373', 'Object Entry': 'OE-10709', 'parent': 'IFA-2008-506'}
{'reference number': 'AF6813', 'Object Entry': 'OE-10710', 'parent': 'IFA-2014-129'}
{'reference number': 'AF6813', 'Object Entry': 'OE-10711', 'parent': 'IFA-2014-129'}
{'reference number': 'AA628', 'Object Entry': 'OE-10712', 'parent': 'IFA (RD) 2016-7'}
{'reference number': 'AD758', 'Object Entry': 'OE-10713', 'parent': 'IFA-2002-463'}
{'reference number': 'AD762', 'Object Entry': 'OE-10714', 'parent': 'IFA-2002-467'}
{'reference number': 'AF6094', 'Object Entry': 'OE-10715', 'parent': 'IFA-2003-072'}
{'reference number': 'AD016', 'Object Entry': 'OE-10716', 'parent': 'IFA (T) 1999-1645'}
{'reference number': 'AF2047', 'Object Entry': 'OE-10717', 'parent': 'IFA-2009-187.309'}
{'reference number': 'AF2926', 'Object Entry': 'OE-10718', 'parent': 'IFA-2010-440'}
{'reference number': 'AF732', 'Object Entry': 'OE-10719', 'parent': 'IFA-2008-99'}
{'reference number': 'AF1270', 'Object Entry': 'OE-10720', 'parent': 'IFA-2006-381.19'}
{'reference number': 'AA402', 'Object Entry': 'OE-10721', 'parent': 'IFA (RD) 2016-3'}
{'reference number': 'AE596', 'Object Entry': 'OE-10722', 'parent': 'IFA-2005-251'}
{'reference number': 'AF418', 'Object Entry': 'OE-10723', 'parent': 'IFA-2007-241'}
{'reference number': 'AF420', 'Object Entry': 'OE-10724', 'parent': 'IFA-2007-259'}
{'reference number': 'AF423', 'Object Entry': 'OE-10725', 'parent': 'IFA-2007-262'}
{'reference number': 'AF483', 'Object Entry': 'OE-10726', 'parent': 'IFA-2007-309'}
{'reference number': 'AF486', 'Object Entry': 'OE-10727', 'parent': 'IFA-2007-312'}
{'reference number': 'AF3147', 'Object Entry': 'OE-10728', 'parent': 'IFA-2010-467'}
{'reference number': 'AF5405', 'Object Entry': 'OE-10729', 'parent': 'IFA-2012-94.24'}
{'reference number': 'AF7943', 'Object Entry': 'OE-10730', 'parent': 'IFA-2011-194.111'}
```

**Comment by kieranjol** [comment]
Also, the `type of acquisition` interview comes after the ` who is the donor` question. The acquisition type question should come first so that if `reproduction` is selected, then the donation questions can be skipped.
