### ISSUE TITLE
SyntaxError: Missing parentheses in call to 'print'. Copyit.py

### ISSUE THREAD

**Issue by b00giehead** [kieranjol/IFIscripts#311]
Editinh my original post now I've learnt something about python... My two problems with copyit.py:
Unable to import 'ififuncs', notified as pylint [E0401]
Undefined variable 'raw_input' [E0602].

I just need to work out how to install pylint in the MacOS python 2.7 to move forward. I think you can close this - sorry to waste your time!

**Comment by kieranjol** [comment]
Closing as I think this is solved.
