### ISSUE TITLE
add uuid option to sipcreator

### ISSUE THREAD

**Issue by raecasey** [kieranjol/IFIscripts#313]
ad an arg parse -uuid that allows the user choose to rename the object and related files to a uuid.

**Comment by kieranjol** [comment]
+1, this should be added ASAP.
Off the top of my head, there already is a uuid option that allows you To specify a uuid for the package rather than getting an auto generated one. So a different argparse name is needed, like rename_uuid or something. Any ideas?

**Comment by kieranjol** [comment]
This PR has the updates - testing would be ideal in order to ensure that this update is what was required: https://github.com/kieranjol/IFIscripts/pull/314

**Comment by raecasey** [comment]
thanks for this - i'll test it out in the next two days and let you know

R

**Comment by kieranjol** [comment]
Indeed,you must
git checkout rename-uuid

**Comment by raecasey** [comment]
thanks, - jeez, that was a fast reply.
i typed in 
git checkout rename-uuid
git checkout rename_uuid
git checkout rename uuid
but i get this return:
fatal: Not a git repository (or any of the parent directories): .git

i am missing some step. Sorry, - I know you've shown me this loads of times
R

**Comment by kieranjol** [comment]
No bother,you need to
cd
Into
Ifigit/ifiscripts

First,then checkout the branch.

**Comment by kieranjol** [comment]
Also, GitHub is saying that the pull request can't be merged. There have been alterations to sipcreator since this branch was created so while it's good that you test this out so that it's as requested, the code will have to change prior to merging.

**Comment by kieranjol** [comment]
Hi Raelene,

I resolved the conflict that was preventing the merging. It would be ideal if you could test this out one more time to ensure that the resolved conflict is still creating the desired output. 

-K
