### ISSUE TITLE
Raspberry Pi command line ImportError: No module named 'lxml'

### ISSUE THREAD

**Issue by digitensions** [kieranjol/IFIscripts#323]
Hi, so following your smart idea I've started trying IFISCRIPTS on RPi, and I've met an error with both validate.py and copyit.py running both scripts via python3:

Traceback (most recent call last):
  File "copyit.py", line 16, in <module>
    import ififuncs
  File "home/pi/ifiscripts/ififuncs.py", line 24, in <module>
    import makedfxml
  File "home/pi/ifiscripts/makedfxml.py", line 9, in <module>
    from lxml import etree
ImportError: No module named 'lxml'

I found another entry about this error and tried a pip install lxml which appears to have downloaded but failed with full install. Wanted to check if this stage is required or do you know of a workaround/something I'm not understanding?

Cheers :)

**Comment by kieranjol** [comment]
EEK
i dunno why pip install lxml isn't working, but I have seen lxml be painful to install in some circumstances.
Can you post the full console output for 
`pip install lxml` 

Would some of these solutions help: https://raspberrypi.stackexchange.com/questions/68894/cant-install-lxml

Also, technically copyit does not need lxml, but ififuncs.py is needed, and that needs lxml for some functions...

**Comment by b00giehead** [comment]
Will do. Is there any way to recall previous terminal print statements? I'll run again and copy paste from raspberry pi either way.

**Comment by kieranjol** [comment]
I don't think so unfortunately..

**Comment by b00giehead** [comment]
I tried some of those apt-get python-dev installs, wasn't able to configure them. The link has slightly different commands so I'll try those :) thanks

**Comment by b00giehead** [comment]
Here's the result of pip install lxml.  Thanks for looking at it :)

pi@raspberrypi:~ $ pip install lxml
Collecting lxml
  Using cached https://files.pythonhosted.org/packages/16/4a/b085a04d6dad79aa5c00c65c9b2bbcb2c6c22e5ac341e7968e0ad2c57e2f/lxml-4.3.0.tar.gz
Building wheels for collected packages: lxml
  Running setup.py bdist_wheel for lxml ... error
  Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-On9TXI/lxml/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpjigOw3pip-wheel- --python-tag cp27:
  Building lxml version 4.3.0.
  Building without Cython.
  ERROR: /bin/sh: 1: xslt-config: not found
  
  ** make sure the development packages of libxml2 and libxslt are installed **
  
  Using build configuration of libxslt
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-armv7l-2.7
  creating build/lib.linux-armv7l-2.7/lxml
  copying src/lxml/__init__.py -> build/lib.linux-armv7l-2.7/lxml
  copying src/lxml/builder.py -> build/lib.linux-armv7l-2.7/lxml
  copying src/lxml/sax.py -> build/lib.linux-armv7l-2.7/lxml
  copying src/lxml/doctestcompare.py -> build/lib.linux-armv7l-2.7/lxml
  copying src/lxml/cssselect.py -> build/lib.linux-armv7l-2.7/lxml
  copying src/lxml/ElementInclude.py -> build/lib.linux-armv7l-2.7/lxml
  copying src/lxml/_elementpath.py -> build/lib.linux-armv7l-2.7/lxml
  copying src/lxml/usedoctest.py -> build/lib.linux-armv7l-2.7/lxml
  copying src/lxml/pyclasslookup.py -> build/lib.linux-armv7l-2.7/lxml
  creating build/lib.linux-armv7l-2.7/lxml/includes
  copying src/lxml/includes/__init__.py -> build/lib.linux-armv7l-2.7/lxml/includes
  creating build/lib.linux-armv7l-2.7/lxml/html
  copying src/lxml/html/diff.py -> build/lib.linux-armv7l-2.7/lxml/html
  copying src/lxml/html/ElementSoup.py -> build/lib.linux-armv7l-2.7/lxml/html
  copying src/lxml/html/__init__.py -> build/lib.linux-armv7l-2.7/lxml/html
  copying src/lxml/html/builder.py -> build/lib.linux-armv7l-2.7/lxml/html
  copying src/lxml/html/soupparser.py -> build/lib.linux-armv7l-2.7/lxml/html
  copying src/lxml/html/html5parser.py -> build/lib.linux-armv7l-2.7/lxml/html
  copying src/lxml/html/_html5builder.py -> build/lib.linux-armv7l-2.7/lxml/html
  copying src/lxml/html/clean.py -> build/lib.linux-armv7l-2.7/lxml/html
  copying src/lxml/html/defs.py -> build/lib.linux-armv7l-2.7/lxml/html
  copying src/lxml/html/usedoctest.py -> build/lib.linux-armv7l-2.7/lxml/html
  copying src/lxml/html/_setmixin.py -> build/lib.linux-armv7l-2.7/lxml/html
  copying src/lxml/html/formfill.py -> build/lib.linux-armv7l-2.7/lxml/html
  copying src/lxml/html/_diffcommand.py -> build/lib.linux-armv7l-2.7/lxml/html
  creating build/lib.linux-armv7l-2.7/lxml/isoschematron
  copying src/lxml/isoschematron/__init__.py -> build/lib.linux-armv7l-2.7/lxml/isoschematron
  copying src/lxml/etree.h -> build/lib.linux-armv7l-2.7/lxml
  copying src/lxml/etree_api.h -> build/lib.linux-armv7l-2.7/lxml
  copying src/lxml/lxml.etree.h -> build/lib.linux-armv7l-2.7/lxml
  copying src/lxml/lxml.etree_api.h -> build/lib.linux-armv7l-2.7/lxml
  copying src/lxml/includes/xslt.pxd -> build/lib.linux-armv7l-2.7/lxml/includes
  copying src/lxml/includes/uri.pxd -> build/lib.linux-armv7l-2.7/lxml/includes
  copying src/lxml/includes/xmlerror.pxd -> build/lib.linux-armv7l-2.7/lxml/includes
  copying src/lxml/includes/xinclude.pxd -> build/lib.linux-armv7l-2.7/lxml/includes
  copying src/lxml/includes/dtdvalid.pxd -> build/lib.linux-armv7l-2.7/lxml/includes
  copying src/lxml/includes/tree.pxd -> build/lib.linux-armv7l-2.7/lxml/includes
  copying src/lxml/includes/htmlparser.pxd -> build/lib.linux-armv7l-2.7/lxml/includes
  copying src/lxml/includes/xmlparser.pxd -> build/lib.linux-armv7l-2.7/lxml/includes
  copying src/lxml/includes/schematron.pxd -> build/lib.linux-armv7l-2.7/lxml/includes
  copying src/lxml/includes/relaxng.pxd -> build/lib.linux-armv7l-2.7/lxml/includes
  copying src/lxml/includes/xmlschema.pxd -> build/lib.linux-armv7l-2.7/lxml/includes
  copying src/lxml/includes/c14n.pxd -> build/lib.linux-armv7l-2.7/lxml/includes
  copying src/lxml/includes/config.pxd -> build/lib.linux-armv7l-2.7/lxml/includes
  copying src/lxml/includes/__init__.pxd -> build/lib.linux-armv7l-2.7/lxml/includes
  copying src/lxml/includes/xpath.pxd -> build/lib.linux-armv7l-2.7/lxml/includes
  copying src/lxml/includes/etreepublic.pxd -> build/lib.linux-armv7l-2.7/lxml/includes
  copying src/lxml/includes/lxml-version.h -> build/lib.linux-armv7l-2.7/lxml/includes
  copying src/lxml/includes/etree_defs.h -> build/lib.linux-armv7l-2.7/lxml/includes
  creating build/lib.linux-armv7l-2.7/lxml/isoschematron/resources
  creating build/lib.linux-armv7l-2.7/lxml/isoschematron/resources/rng
  copying src/lxml/isoschematron/resources/rng/iso-schematron.rng -> build/lib.linux-armv7l-2.7/lxml/isoschematron/resources/rng
  creating build/lib.linux-armv7l-2.7/lxml/isoschematron/resources/xsl
  copying src/lxml/isoschematron/resources/xsl/RNG2Schtrn.xsl -> build/lib.linux-armv7l-2.7/lxml/isoschematron/resources/xsl
  copying src/lxml/isoschematron/resources/xsl/XSD2Schtrn.xsl -> build/lib.linux-armv7l-2.7/lxml/isoschematron/resources/xsl
  creating build/lib.linux-armv7l-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
  copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_dsdl_include.xsl -> build/lib.linux-armv7l-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
  copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_abstract_expand.xsl -> build/lib.linux-armv7l-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
  copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_schematron_message.xsl -> build/lib.linux-armv7l-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
  copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_svrl_for_xslt1.xsl -> build/lib.linux-armv7l-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
  copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_schematron_skeleton_for_xslt1.xsl -> build/lib.linux-armv7l-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
  copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/readme.txt -> build/lib.linux-armv7l-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
  running build_ext
  building 'lxml.etree' extension
  creating build/temp.linux-armv7l-2.7
  creating build/temp.linux-armv7l-2.7/src
  creating build/temp.linux-armv7l-2.7/src/lxml
  arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-Ub3vap/python2.7-2.7.13=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -DCYTHON_CLINE_IN_TRACEBACK=0 -Isrc -Isrc/lxml/includes -I/usr/include/python2.7 -c src/lxml/etree.c -o build/temp.linux-armv7l-2.7/src/lxml/etree.o -w
  In file included from src/lxml/etree.c:707:0:
  src/lxml/includes/etree_defs.h:14:31: fatal error: libxml/xmlversion.h: No such file or directory
   #include "libxml/xmlversion.h"
                                 ^
  compilation terminated.
  Compile failed: command 'arm-linux-gnueabihf-gcc' failed with exit status 1
  creating tmp
  cc -I/usr/include/libxml2 -c /tmp/xmlXPathInitzUwkYX.c -o tmp/xmlXPathInitzUwkYX.o
  /tmp/xmlXPathInitzUwkYX.c:1:26: fatal error: libxml/xpath.h: No such file or directory
   #include "libxml/xpath.h"
                            ^
  compilation terminated.
  *********************************************************************************
  Could not find function xmlCheckVersion in library libxml2. Is libxml2 installed?
  *********************************************************************************
  error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for lxml
  Running setup.py clean for lxml
Failed to build lxml
Installing collected packages: lxml
  Running setup.py install for lxml ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-On9TXI/lxml/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-RdcB1C-record/install-record.txt --single-version-externally-managed --compile --user --prefix=:
    Building lxml version 4.3.0.
    Building without Cython.
    ERROR: /bin/sh: 1: xslt-config: not found
    
    ** make sure the development packages of libxml2 and libxslt are installed **
    
    Using build configuration of libxslt
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-armv7l-2.7
    creating build/lib.linux-armv7l-2.7/lxml
    copying src/lxml/__init__.py -> build/lib.linux-armv7l-2.7/lxml
    copying src/lxml/builder.py -> build/lib.linux-armv7l-2.7/lxml
    copying src/lxml/sax.py -> build/lib.linux-armv7l-2.7/lxml
    copying src/lxml/doctestcompare.py -> build/lib.linux-armv7l-2.7/lxml
    copying src/lxml/cssselect.py -> build/lib.linux-armv7l-2.7/lxml
    copying src/lxml/ElementInclude.py -> build/lib.linux-armv7l-2.7/lxml
    copying src/lxml/_elementpath.py -> build/lib.linux-armv7l-2.7/lxml
    copying src/lxml/usedoctest.py -> build/lib.linux-armv7l-2.7/lxml
    copying src/lxml/pyclasslookup.py -> build/lib.linux-armv7l-2.7/lxml
    creating build/lib.linux-armv7l-2.7/lxml/includes
    copying src/lxml/includes/__init__.py -> build/lib.linux-armv7l-2.7/lxml/includes
    creating build/lib.linux-armv7l-2.7/lxml/html
    copying src/lxml/html/diff.py -> build/lib.linux-armv7l-2.7/lxml/html
    copying src/lxml/html/ElementSoup.py -> build/lib.linux-armv7l-2.7/lxml/html
    copying src/lxml/html/__init__.py -> build/lib.linux-armv7l-2.7/lxml/html
    copying src/lxml/html/builder.py -> build/lib.linux-armv7l-2.7/lxml/html
    copying src/lxml/html/soupparser.py -> build/lib.linux-armv7l-2.7/lxml/html
    copying src/lxml/html/html5parser.py -> build/lib.linux-armv7l-2.7/lxml/html
    copying src/lxml/html/_html5builder.py -> build/lib.linux-armv7l-2.7/lxml/html
    copying src/lxml/html/clean.py -> build/lib.linux-armv7l-2.7/lxml/html
    copying src/lxml/html/defs.py -> build/lib.linux-armv7l-2.7/lxml/html
    copying src/lxml/html/usedoctest.py -> build/lib.linux-armv7l-2.7/lxml/html
    copying src/lxml/html/_setmixin.py -> build/lib.linux-armv7l-2.7/lxml/html
    copying src/lxml/html/formfill.py -> build/lib.linux-armv7l-2.7/lxml/html
    copying src/lxml/html/_diffcommand.py -> build/lib.linux-armv7l-2.7/lxml/html
    creating build/lib.linux-armv7l-2.7/lxml/isoschematron
    copying src/lxml/isoschematron/__init__.py -> build/lib.linux-armv7l-2.7/lxml/isoschematron
    copying src/lxml/etree.h -> build/lib.linux-armv7l-2.7/lxml
    copying src/lxml/etree_api.h -> build/lib.linux-armv7l-2.7/lxml
    copying src/lxml/lxml.etree.h -> build/lib.linux-armv7l-2.7/lxml
    copying src/lxml/lxml.etree_api.h -> build/lib.linux-armv7l-2.7/lxml
    copying src/lxml/includes/xslt.pxd -> build/lib.linux-armv7l-2.7/lxml/includes
    copying src/lxml/includes/uri.pxd -> build/lib.linux-armv7l-2.7/lxml/includes
    copying src/lxml/includes/xmlerror.pxd -> build/lib.linux-armv7l-2.7/lxml/includes
    copying src/lxml/includes/xinclude.pxd -> build/lib.linux-armv7l-2.7/lxml/includes
    copying src/lxml/includes/dtdvalid.pxd -> build/lib.linux-armv7l-2.7/lxml/includes
    copying src/lxml/includes/tree.pxd -> build/lib.linux-armv7l-2.7/lxml/includes
    copying src/lxml/includes/htmlparser.pxd -> build/lib.linux-armv7l-2.7/lxml/includes
    copying src/lxml/includes/xmlparser.pxd -> build/lib.linux-armv7l-2.7/lxml/includes
    copying src/lxml/includes/schematron.pxd -> build/lib.linux-armv7l-2.7/lxml/includes
    copying src/lxml/includes/relaxng.pxd -> build/lib.linux-armv7l-2.7/lxml/includes
    copying src/lxml/includes/xmlschema.pxd -> build/lib.linux-armv7l-2.7/lxml/includes
    copying src/lxml/includes/c14n.pxd -> build/lib.linux-armv7l-2.7/lxml/includes
    copying src/lxml/includes/config.pxd -> build/lib.linux-armv7l-2.7/lxml/includes
    copying src/lxml/includes/__init__.pxd -> build/lib.linux-armv7l-2.7/lxml/includes
    copying src/lxml/includes/xpath.pxd -> build/lib.linux-armv7l-2.7/lxml/includes
    copying src/lxml/includes/etreepublic.pxd -> build/lib.linux-armv7l-2.7/lxml/includes
    copying src/lxml/includes/lxml-version.h -> build/lib.linux-armv7l-2.7/lxml/includes
    copying src/lxml/includes/etree_defs.h -> build/lib.linux-armv7l-2.7/lxml/includes
    creating build/lib.linux-armv7l-2.7/lxml/isoschematron/resources
    creating build/lib.linux-armv7l-2.7/lxml/isoschematron/resources/rng
    copying src/lxml/isoschematron/resources/rng/iso-schematron.rng -> build/lib.linux-armv7l-2.7/lxml/isoschematron/resources/rng
    creating build/lib.linux-armv7l-2.7/lxml/isoschematron/resources/xsl
    copying src/lxml/isoschematron/resources/xsl/RNG2Schtrn.xsl -> build/lib.linux-armv7l-2.7/lxml/isoschematron/resources/xsl
    copying src/lxml/isoschematron/resources/xsl/XSD2Schtrn.xsl -> build/lib.linux-armv7l-2.7/lxml/isoschematron/resources/xsl
    creating build/lib.linux-armv7l-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
    copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_dsdl_include.xsl -> build/lib.linux-armv7l-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
    copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_abstract_expand.xsl -> build/lib.linux-armv7l-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
    copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_schematron_message.xsl -> build/lib.linux-armv7l-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
    copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_svrl_for_xslt1.xsl -> build/lib.linux-armv7l-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
    copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_schematron_skeleton_for_xslt1.xsl -> build/lib.linux-armv7l-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
    copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/readme.txt -> build/lib.linux-armv7l-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
    running build_ext
    building 'lxml.etree' extension
    creating build/temp.linux-armv7l-2.7
    creating build/temp.linux-armv7l-2.7/src
    creating build/temp.linux-armv7l-2.7/src/lxml
    arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-Ub3vap/python2.7-2.7.13=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -DCYTHON_CLINE_IN_TRACEBACK=0 -Isrc -Isrc/lxml/includes -I/usr/include/python2.7 -c src/lxml/etree.c -o build/temp.linux-armv7l-2.7/src/lxml/etree.o -w
    In file included from src/lxml/etree.c:707:0:
    src/lxml/includes/etree_defs.h:14:31: fatal error: libxml/xmlversion.h: No such file or directory
     #include "libxml/xmlversion.h"
                                   ^
    compilation terminated.
    Compile failed: command 'arm-linux-gnueabihf-gcc' failed with exit status 1
    cc -I/usr/include/libxml2 -c /tmp/xmlXPathInits_hWTy.c -o tmp/xmlXPathInits_hWTy.o
    /tmp/xmlXPathInits_hWTy.c:1:26: fatal error: libxml/xpath.h: No such file or directory
     #include "libxml/xpath.h"
                              ^
    compilation terminated.
    *********************************************************************************
    Could not find function xmlCheckVersion in library libxml2. Is libxml2 installed?
    *********************************************************************************
    error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-On9TXI/lxml/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-RdcB1C-record/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-build-On9TXI/lxml/

**Comment by digitensions** [comment]
I'm going to close this as I suspect the error is my complete lack of understanding :)
