### ISSUE TITLE
copyit line-endings are causing false fixity failure reports

### ISSUE THREAD

**Issue by kieranjol** [kieranjol/IFIscripts#327]
As reported by @b00giehead:
copyit will sometimes say that the manifests were not identical, even though the only difference is line endings.

This change in line endings happened around the time of the python3 fixes, where I stopped opening text files in binary mode. Opening textfiles in binary mode on python2 was an easy way to make sure that Windows and Unix would use the same line endings, but that has all changed now.
Joanna and I have both noticed that a manifest made in windows can trigger this warning if copyit is used on OSX, and maybe vice-versa.
I am pretty sure that I've just encountered an issue where a manifest made on Windows prior to this change has now triggered the issue after a copyit transfer.

The solution is most likely to just ignore newlines when comparing manifests. This should be simple - I THINK????

**Comment by kieranjol** [comment]
https://github.com/kieranjol/IFIscripts/blob/master/copyit.py#L573 this is the line in particular.

So this page might have an answer but heavy testing is needed: https://stackoverflow.com/questions/42981652/how-to-ignore-different-newline-char-with-python-filecmp

**Comment by kieranjol** [comment]
I added a much more general method of comparison that ignores line endings, thanks for reporting this @b00giehead

**Comment by b00giehead** [comment]
Thanks Kieran. I’ll try this when back in office next week :)
