### ISSUE TITLE
add yujing to user argument/'who are you?' question

### ISSUE THREAD

**Issue by raecasey** [kieranjol/IFIscripts#336]
Hi
could you add Yujing to the user argument/'who are you?' question?
Yujing Huang

i tried looking for it, but couldn't find it. I'm guessing it's a function?
Maybe you could point me to it so that i can add Thomas when he starts and others, - that way i can just send pull requests to you rather than you having to do it yourself.

cheers
R

**Comment by kieranjol** [comment]
https://github.com/kieranjol/IFIscripts/blob/822b2c508370a9af2b25838e4dca450bcbaf878d/ififuncs.py#L704

Aye, it's right here in IFIfuncs - I think you'll need to add the name in three different areas. Maybe search for 'Wentao Ma' to get an idea of where you'll need to add.

**Comment by raecasey** [comment]
cool, - ta verry much

**Comment by kieranjol** [comment]
savageeeee
