### ISSUE TITLE
 accession.py/batchaccession.py -reproduction creator

### ISSUE THREAD

**Issue by raecasey** [kieranjol/IFIscripts#344]
could we add an argument to accession.py -reproduction_creator that is then made into a question in batchaccession.py
'Who is the Reproduction Creator? Not applicable for acquisitions.'
Are you really sure? Y?N

Again this would cut down on our need to open and modify the pbcore in libre office or make manual changes to the database.
we'd have to decide whether we input a string as an answer or use the user function, but add some post houses to it. Cinelab, Restore, Screen Scene etc.
For the moment a string is probably easier as sometimes there are mulitple reproducers, - i.e. Gavin and Brian together, I've been writing: -  Gavin Martin (2002), Brian Cash (2016). But it would be important to get consistency with names. especially the post houses. Screen Scene Ltd. - that sort of thing.
We'd also need to decide what to write in the case of reproductions where the reproducer is unknown. either 'unknown' or just type in n/a

R

**Comment by kieranjol** [comment]
ok gonna work on this now - soz!

**Comment by kieranjol** [comment]
Should be fixed in https://github.com/kieranjol/IFIscripts/commit/08fbfb39987ebce499b1a17c7d2bc7a13622e45c
