### ISSUE TITLE
normalise - completely broken without the -sip option

### ISSUE THREAD

**Issue by kieranjol** [kieranjol/IFIscripts#346]
normalise errors out due to an OE variable not being assigned. This has most likely slipped through the cracks due to us always using the `-sip` option :(

**Comment by digitensions** [comment]
I think this is the error I’ve been experiencing! I’ll try again when it’s updated, thank you.

**Comment by kieranjol** [comment]
Cool, this is pretty embarrassing!

**Comment by kieranjol** [comment]
Fixed, thank you so much for reporting this initially!
