### ISSUE TITLE
dcpaccess.py - help argument not working

### ISSUE THREAD

**Issue by raecasey** [kieranjol/IFIscripts#349]
have only tried this on es2, - 
the script works fine,  - but i just can't pull up the -h argument
[dcpaccess-h.txt](https://github.com/kieranjol/IFIscripts/files/3339037/dcpaccess-h.txt)
terminal output attached

**Comment by kieranjol** [comment]
Thanks for reporting this - looks like this commit a few months back broke the -h due to the addition of a percent sign https://github.com/kieranjol/IFIscripts/commit/7e03ee8318b2dc362a9507129911976001eb0f88#diff-d121e0970fc71176667b48066905b025R57

**Comment by kieranjol** [comment]
Anyhow this is fixed.
