### ISSUE TITLE
merge_sorted script

### ISSUE THREAD

**Issue by raecasey** [kieranjol/IFIscripts#353]
create a new script that works just like mergepbcore.py, but works on the individual register.csv documents (e.g. register_2019-07-10T14_52_59.csv) that land on in the ifiscripts folder when individual accession.py or sipcreator.py -accession scripts are run.

Would be somethign like:
mergesorted.py (directory containing multiple individual register.csvs)
returns: Merged Sorted CSV is stored in /Users/edit/Desktop/ifiscripts_logs/2019-07-10T16_45_29_sorted.csv

this can then be used for accession_register.py along with pbcore_csv and folmo_csv

would be handy for radharc sd tape workflow
and potentially Gavin's also.

**Comment by kieranjol** [comment]
Added here - https://github.com/kieranjol/IFIscripts/commit/d520decc0faaa25a809b068672ee2e0f98039d26
