### ISSUE TITLE
batch sipcreator

### ISSUE THREAD

**Issue by kieranjol** [kieranjol/IFIscripts#355]
So we have a bunch of repetitive sip-creations coming up with the AS-11 stuff. These will usually follow a pattern of:
`MXF+SIDECAR XML +MAYBE STL` and then it gets increasingly more complex with later deliveries.

My proposal is:

* Add a `-batch` option
    * `-batch` will cause sipcreator to behave differently
    * it will expect your input to be a series of folders. It will assume that the video file is what goes in `objects`, equivalent to the current behaviour of the `-i` option
    * It will ask you what the starting OE number is, and it will then auto-increment by 1 for each folder.
* Add a `-supplement_extension_pattern` option (other name ideas are appreciated)
    * This option takes a one or more extensions as the argument. eg `-supplement_extension xml pdf` will take all xml and pdf files that are in the folder with the video file add add them to the extension folder
* The STLs are the only other files that will go into  `objects` so there's at least two ways of dealing with those:
    * If STL is detected along with an MXF, then just add the STL along with the MXF into the objects folder
    * Otherwise, we add an `-object_extension_pattern` (again, terrible name)  which allows you to stipulate what file extensions should be scooped up along with the video file.

I think it's a flip of a coin really, probably better not to hard code too many things into sipcreator and keep it all super flexible.

What do ye think? It should not take much effort to implement this as I can reuse the code from `normalise.py`

**Comment by kieranjol** [comment]
P.S I think this could potentially be extended to DCPs as well but I haven't thought that far ahead.
The main work here will be in pre-sorting/categorising manually if needs be.

**Comment by kieranjol** [comment]
Of course the other option is to create a `batchsipcreator` option which might end up being the easiest thing to do.

**Comment by raecasey** [comment]
I think this is a great idea.
maybe the batchsipcreate is the way to go, - that way you could have different arguments coming out of it for different cases.
examples being
as11
dcp
a batch of av files with one sidecar - ( e.g. engineers reports for tape captures or gavins legacy sd telecines
a batch of av files with multiple supplements gathered in a  sidecar folder -e.g. - supplementary material coming back from specialist av or elsewhere

if the basic foundation script is created then it can be build on as we need these cases or come across more examples, - potentially even pulling in a seq2ffv1/rawcooked argument that could batch sipcreate the adverts or other batches of image sequences.

anyway, - I think especially for as11, - its a great idea and I think we'd find great use for this script

R

**Comment by kieranjol** [comment]
Ok, batchsipcreator it is! I think it's a lot easier to do it that way in general,and seeing as sipcreator is quite stable right now, it is best to just write a seperate script that sits on top of it. I like the idea of different arguments as well. I'll take a shtab at this when I get the chance,thanks for the feedback!

**Comment by kieranjol** [comment]
Resolved https://github.com/kieranjol/IFIscripts/commit/ff193ab0146f47dca7d918745c48426213802111
