### ISSUE TITLE
batchsipcreator -add rename_uuid

### ISSUE THREAD

**Issue by raecasey** [kieranjol/IFIscripts#371]
Add re_name uuid argument to batchsipcreator.py for ballymun workflow

**Comment by kieranjol** [comment]
Hey, i'm silly - I actually added this from the very beginning but never had to use it. I just didn't notice yesterday when doing the run-through - https://github.com/kieranjol/IFIscripts/blob/master/batchsipcreator.py#L31

**Comment by raecasey** [comment]
brilliant, thanks
