### ISSUE TITLE
makedip.py - add sip package argument

### ISSUE THREAD

**Issue by raecasey** [kieranjol/IFIscripts#374]
add an argument to makedip.py so that it can be used on a sip package, taking the present oe-number as the file name for the proxy instead of the absent aaa accession number.

argument could be called -sip_name

Raelene

**Comment by kieranjol** [comment]
Hi Raelene - this is added now, soz for the delay - didn't see this notification at all. I didn't add an argument as it was possible to just make this the default behaviour - use aaa or oe number depending on source.

**Comment by raecasey** [comment]
great, - thanks for that.
R
