### ISSUE TITLE
makedip.py with w/m and bitc

### ISSUE THREAD

**Issue by raecasey** [kieranjol/IFIscripts#381]
Hi

makedip.py seems to inherit the clean argument from bitc.py as a default. which is great.
could you make an argument so that the watermark and bitc can be applied if required?
i could do it using bitc.py but the objects are sipped and i want the bitcs to inherit the oe number so i'd have to change their filename first which is messy.
this is for vimeo copies of ballymun files for ballymun communications

cheers
R

**Comment by kieranjol** [comment]
Hi Raelene - I'll give it a go anyhow, it's a good idea.

**Comment by kieranjol** [comment]
Hey - it took a bit more work as i needed to change around some stuff to make the code flexible enough. We should now be able to alter makedip more easily should more flags be needed: https://github.com/kieranjol/IFIscripts/commit/cbda2cb2764d2a0b6b992c71deed509d8e3d26ac

If you run update.py, the fix should be there. I tested it with wide, bitc and no extra args and all seemed well.

**Comment by kieranjol** [comment]
eek - the arg is `-bitc`

**Comment by raecasey** [comment]
just tested that out, - works great, thanks.
will be really useful for creating filmos from sips in projects

**Comment by kieranjol** [comment]
Yay! Glad to hear it.
