### ISSUE TITLE
manifest.py script break

### ISSUE THREAD

**Issue by raecasey** [kieranjol/IFIscripts#388]
here's the terminal output:

Last login: Sat Jul 25 14:20:19 on ttys005
ifi-mac-pro:~ admin$ manifest.py -s /Volumes/Stardom\ 1/to_be_sipped_and_sorted/Moving\ Media\ Digitization\ Project\ Files\ April\ 2016
Traceback (most recent call last):
  File "/Users/admin/ifigit/ifiscripts/manifest.py", line 164, in <module>
    main(sys.argv[1:])
  File "/Users/admin/ifigit/ifiscripts/manifest.py", line 97, in main
    generate_log(log_name_source, 'manifest.py started.')
  File "/Users/admin/ifigit/ifiscripts/ififuncs.py", line 312, in generate_log
    with open(log, "w", encoding='utf-8') as fo:
TypeError: 'encoding' is an invalid keyword argument for this function
ifi-mac-pro:~ admin$

**Comment by kieranjol** [comment]
Hi Raelene - it's a unicode issue - I'd need filenames to figure out how to figure this out. I tried logging on to ES2 but couldn't find the paths in question so can you point me in the right direction please?

**Comment by raecasey** [comment]
Hi Kieran

the example I gave you above was from the stardom drive which is now disconnected. i'm pasting a new example below from ES2 desktop. it break has happened to me on macmini and es1 also in the last few weeks. let me know if you would like me to post more examples. - from different stations or with different av content. R

terminal:
Last login: Fri Jul 31 13:39:49 on ttys005
ifi-mac-pro:~ admin$ manifest.py -h
usage: manifest.py [-h] [-s] [-f] [-sha512] source

Generate manifest with checksums for a directory Written by Kieran O'Leary.

positional arguments:
  source        Input directory

optional arguments:
  -h, --help    show this help message and exit
  -s, -sidecar  Generates Sidecar
  -f, -felix    Felix Meehan workflow - places manifest inside of source
                directory
  -sha512       Generates sha512 checksums instead of md5
ifi-mac-pro:~ admin$ manifest.py -s /Users/admin/Desktop/rc_desktop/eu_blarney_qc/ucla/tiff_relevants 
Traceback (most recent call last):
  File "/Users/admin/ifigit/ifiscripts/manifest.py", line 164, in <module>
    main(sys.argv[1:])
  File "/Users/admin/ifigit/ifiscripts/manifest.py", line 97, in main
    generate_log(log_name_source, 'manifest.py started.')
  File "/Users/admin/ifigit/ifiscripts/ififuncs.py", line 312, in generate_log
    with open(log, "w", encoding='utf-8') as fo:
TypeError: 'encoding' is an invalid keyword argument for this function
ifi-mac-pro:~ admin$

**Comment by kieranjol** [comment]
So this was weird - i didn't have the correct python3 shebang at the top, and python2 was running the script, not python3. All is fixed now. Thx for reporting.
