### ISSUE TITLE
move.py - Check if enough free space in destination

### ISSUE THREAD

**Issue by kieranjol** [kieranjol/IFIscripts#43]
^^

**Comment by kieranjol** [comment]
I don't think python has an `os` command that will work for all operating system. perhaps parsing the output via a `subprocess` call is the way to go, with a different call per operating system? Anyhow this is totally worthwhile doing. I think we've had at least one instance where a long move.py process has been running for 24 hours only to run out of space.

**Comment by kieranjol** [comment]
This should probably be implemented.

**Comment by AnjaMahler** [comment]
Can we implement please? -- One step less in my manual workflow :)

**Comment by kieranjol** [comment]
Ok will do!

On 24 Aug 2017 14:57, "AnjaMahler" <notifications@github.com> wrote:

Can we implement please? -- One step less in my manual workflow :)

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/kieranjol/IFIscripts/issues/43#issuecomment-324642915>,
or mute the thread

**Comment by kieranjol** [comment]
OK I'm going to raise the priority of this to BUG level and fix it soon.
