### ISSUE TITLE
all aip-y scripts - include the script in a subdirectory

### ISSUE THREAD

**Issue by kieranjol** [kieranjol/IFIscripts#69]
We should be able to just use sys.argv[0] to copy the script wherever. Thanks to @vphill for the idea.

**Comment by kieranjol** [comment]
I'm currently grabbing the git commit hash and datetime which should be enough to point to the version of a script that was run. Less messy than inserting the script.

**Comment by raecasey** [comment]
nice - good thinking

**Comment by kieranjol** [comment]
:+1:
