### ISSUE TITLE
option to create without destination manifest / just detination manifest

### ISSUE THREAD

**Issue by AnjaMahler** [kieranjol/IFIscripts#70]
For DCDM's to save time can we have an option to option to create ~without destination manifest  ~ just detination manifest?

**Comment by kieranjol** [comment]
Hey, thanks for raising this as well - we need to do this. I didn't think of adding that option, I think that's actually the best/easiest way to do it for now.
We can probably either alter move.py, or create a verify.py script to do the destionation manifest check if needs be.

**Comment by kieranjol** [comment]
Also, doing a manual check with md5deep is very simple if it comes to it
`md5deep -ler drivename > manifest.md5` - then we can compare afterwards.

**Comment by kieranjol** [comment]
also lol I only fixed this after @AnjaMahler is not even with the IFI anymore! :(
