### ISSUE TITLE
moveit.py - add progress indicator

### ISSUE THREAD

**Issue by kieranjol** [kieranjol/IFIscripts#91]
As we've moved from md5deep, we need a progress indicator. This or something similar might work @ecodonohoe ??

**Comment by ecodonohoe** [comment]
Yep, I'll start looking into the progress package and any other options I come across.

**Comment by kieranjol** [comment]
Awesome!

**Comment by kieranjol** [comment]
Thanks @ecodonohoe for adding this - closing.
